#!/usr/bin/env python3
import requests
import json
import sys

if len(sys.argv) < 2:
    print('you need to provide an asn to lookup: asn <asn_number>')
    sys.exit(1)

asn = sys.argv[1]
url = "https://whois.arin.net/rest/asn/AS" + asn + ".json"

result = requests.get(url)

if result.status_code != 200:
    print("couldn't find that ASN")
    sys.exit(1)

json_results = json.loads(result.text)
name = json_results['asn']['orgRef']['@name']
print(name)
