#!/usr/bin/env python3

import pyautogui
import time
import sys
from datetime import datetime
pyautogui.FAILSAFE = False
numMin = None
if ((len(sys.argv) < 2) or sys.argv[1].isalpha() or int(sys.argv[1]) < 1):
    numMin = 3
else:
    numMin = int(sys.argv[1])
while(True):
    now = datetime.now()
    current_time = now.strftime("%H")
    if int(current_time) >= 17:
        print("Quiting time...")
        sys.exit(1)
    x = 0
    while(x < numMin):
        time.sleep(60)
        x += 1
    for i in range(0, 200):
        pyautogui.moveTo(0, i*4)
    pyautogui.moveTo(1, 1)
    for i in range(0, 3):
        pyautogui.press("shift")
    print("Movement made at {}".format(datetime.now().time()))
